CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    form_id BIGINT NOT NULL,
    text VARCHAR(255) NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (id),
    CONSTRAINT fk_questions_forms FOREIGN KEY (form_id) REFERENCES forms(id)
);