CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id BIGINT NOT NULL,
    answers_set_id BIGINT NOT NULL,
    text VARCHAR(255) NOT NULL,
    CONSTRAINT pk_answers PRIMARY KEY (id),
    CONSTRAINT fk_answers_questions FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_answers_answers_sets FOREIGN KEY (answers_set_id) REFERENCES answers_sets(id)
);