CREATE TABLE answers_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    form_id BIGINT NOT NULL,
    CONSTRAINT pk_answers_set PRIMARY KEY (id),
    CONSTRAINT fk_answers_set_form FOREIGN KEY (form_id) REFERENCES forms(id)
);